load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_library")

jsonnet_library(
    name = "lib",
    visibility = [
        "//visibility:public"
    ],
    srcs = [
        "terraform.libsonnet",
    ],
)
